/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VehiclesRouteImport } from './routes/vehicles'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RequestAccessRouteImport } from './routes/request-access'
import { Route as ReportRouteImport } from './routes/report'
import { Route as MyCarRouteImport } from './routes/my-car'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MyCarIndexRouteImport } from './routes/my-car.index'
import { Route as VehiclesUnitIdRouteImport } from './routes/vehicles.$unitId'
import { Route as MyCarHistoryRouteImport } from './routes/my-car.history'
import { Route as MyCarBookRouteImport } from './routes/my-car.book'
import { Route as MyCarAppointmentsRouteImport } from './routes/my-car.appointments'
import { Route as AdminWalkinRouteImport } from './routes/admin.walkin'
import { Route as AdminVehiclesRouteImport } from './routes/admin.vehicles'
import { Route as AdminServiceLogRouteImport } from './routes/admin.service-log'
import { Route as AdminSelectRouteImport } from './routes/admin.select'
import { Route as AdminSchedulesRouteImport } from './routes/admin.schedules'
import { Route as AdminRequestsRouteImport } from './routes/admin.requests'
import { Route as AdminPricingRouteImport } from './routes/admin.pricing'
import { Route as AdminClientsRouteImport } from './routes/admin.clients'
import { Route as AdminAppointmentsRouteImport } from './routes/admin.appointments'
import { Route as AdminWalkinIndexRouteImport } from './routes/admin.walkin.index'
import { Route as AdminWalkinVehiclesRouteImport } from './routes/admin.walkin.vehicles'
import { Route as AdminWalkinSchedulesRouteImport } from './routes/admin.walkin.schedules'
import { Route as AdminWalkinRemindersRouteImport } from './routes/admin.walkin.reminders'
import { Route as AdminWalkinCustomersRouteImport } from './routes/admin.walkin.customers'
import { Route as AdminWalkinAppointmentsRouteImport } from './routes/admin.walkin.appointments'
import { Route as AdminWalkinVehiclesVehicleIdRouteImport } from './routes/admin.walkin.vehicles.$vehicleId'
import { Route as AdminWalkinCustomersCustomerIdRouteImport } from './routes/admin.walkin.customers.$customerId'

const VehiclesRoute = VehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestAccessRoute = RequestAccessRouteImport.update({
  id: '/request-access',
  path: '/request-access',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const MyCarRoute = MyCarRouteImport.update({
  id: '/my-car',
  path: '/my-car',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyCarIndexRoute = MyCarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MyCarRoute,
} as any)
const VehiclesUnitIdRoute = VehiclesUnitIdRouteImport.update({
  id: '/$unitId',
  path: '/$unitId',
  getParentRoute: () => VehiclesRoute,
} as any)
const MyCarHistoryRoute = MyCarHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => MyCarRoute,
} as any)
const MyCarBookRoute = MyCarBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => MyCarRoute,
} as any)
const MyCarAppointmentsRoute = MyCarAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => MyCarRoute,
} as any)
const AdminWalkinRoute = AdminWalkinRouteImport.update({
  id: '/walkin',
  path: '/walkin',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVehiclesRoute = AdminVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServiceLogRoute = AdminServiceLogRouteImport.update({
  id: '/service-log',
  path: '/service-log',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSelectRoute = AdminSelectRouteImport.update({
  id: '/select',
  path: '/select',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSchedulesRoute = AdminSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAppointmentsRoute = AdminAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWalkinIndexRoute = AdminWalkinIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminWalkinRoute,
} as any)
const AdminWalkinVehiclesRoute = AdminWalkinVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AdminWalkinRoute,
} as any)
const AdminWalkinSchedulesRoute = AdminWalkinSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => AdminWalkinRoute,
} as any)
const AdminWalkinRemindersRoute = AdminWalkinRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AdminWalkinRoute,
} as any)
const AdminWalkinCustomersRoute = AdminWalkinCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminWalkinRoute,
} as any)
const AdminWalkinAppointmentsRoute = AdminWalkinAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AdminWalkinRoute,
} as any)
const AdminWalkinVehiclesVehicleIdRoute =
  AdminWalkinVehiclesVehicleIdRouteImport.update({
    id: '/$vehicleId',
    path: '/$vehicleId',
    getParentRoute: () => AdminWalkinVehiclesRoute,
  } as any)
const AdminWalkinCustomersCustomerIdRoute =
  AdminWalkinCustomersCustomerIdRouteImport.update({
    id: '/$customerId',
    path: '/$customerId',
    getParentRoute: () => AdminWalkinCustomersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/my-car': typeof MyCarRouteWithChildren
  '/report': typeof ReportRoute
  '/request-access': typeof RequestAccessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/vehicles': typeof VehiclesRouteWithChildren
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/schedules': typeof AdminSchedulesRoute
  '/admin/select': typeof AdminSelectRoute
  '/admin/service-log': typeof AdminServiceLogRoute
  '/admin/vehicles': typeof AdminVehiclesRoute
  '/admin/walkin': typeof AdminWalkinRouteWithChildren
  '/my-car/appointments': typeof MyCarAppointmentsRoute
  '/my-car/book': typeof MyCarBookRoute
  '/my-car/history': typeof MyCarHistoryRoute
  '/vehicles/$unitId': typeof VehiclesUnitIdRoute
  '/my-car/': typeof MyCarIndexRoute
  '/admin/walkin/appointments': typeof AdminWalkinAppointmentsRoute
  '/admin/walkin/customers': typeof AdminWalkinCustomersRouteWithChildren
  '/admin/walkin/reminders': typeof AdminWalkinRemindersRoute
  '/admin/walkin/schedules': typeof AdminWalkinSchedulesRoute
  '/admin/walkin/vehicles': typeof AdminWalkinVehiclesRouteWithChildren
  '/admin/walkin/': typeof AdminWalkinIndexRoute
  '/admin/walkin/customers/$customerId': typeof AdminWalkinCustomersCustomerIdRoute
  '/admin/walkin/vehicles/$vehicleId': typeof AdminWalkinVehiclesVehicleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/report': typeof ReportRoute
  '/request-access': typeof RequestAccessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/vehicles': typeof VehiclesRouteWithChildren
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/schedules': typeof AdminSchedulesRoute
  '/admin/select': typeof AdminSelectRoute
  '/admin/service-log': typeof AdminServiceLogRoute
  '/admin/vehicles': typeof AdminVehiclesRoute
  '/my-car/appointments': typeof MyCarAppointmentsRoute
  '/my-car/book': typeof MyCarBookRoute
  '/my-car/history': typeof MyCarHistoryRoute
  '/vehicles/$unitId': typeof VehiclesUnitIdRoute
  '/my-car': typeof MyCarIndexRoute
  '/admin/walkin/appointments': typeof AdminWalkinAppointmentsRoute
  '/admin/walkin/customers': typeof AdminWalkinCustomersRouteWithChildren
  '/admin/walkin/reminders': typeof AdminWalkinRemindersRoute
  '/admin/walkin/schedules': typeof AdminWalkinSchedulesRoute
  '/admin/walkin/vehicles': typeof AdminWalkinVehiclesRouteWithChildren
  '/admin/walkin': typeof AdminWalkinIndexRoute
  '/admin/walkin/customers/$customerId': typeof AdminWalkinCustomersCustomerIdRoute
  '/admin/walkin/vehicles/$vehicleId': typeof AdminWalkinVehiclesVehicleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/my-car': typeof MyCarRouteWithChildren
  '/report': typeof ReportRoute
  '/request-access': typeof RequestAccessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/vehicles': typeof VehiclesRouteWithChildren
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/schedules': typeof AdminSchedulesRoute
  '/admin/select': typeof AdminSelectRoute
  '/admin/service-log': typeof AdminServiceLogRoute
  '/admin/vehicles': typeof AdminVehiclesRoute
  '/admin/walkin': typeof AdminWalkinRouteWithChildren
  '/my-car/appointments': typeof MyCarAppointmentsRoute
  '/my-car/book': typeof MyCarBookRoute
  '/my-car/history': typeof MyCarHistoryRoute
  '/vehicles/$unitId': typeof VehiclesUnitIdRoute
  '/my-car/': typeof MyCarIndexRoute
  '/admin/walkin/appointments': typeof AdminWalkinAppointmentsRoute
  '/admin/walkin/customers': typeof AdminWalkinCustomersRouteWithChildren
  '/admin/walkin/reminders': typeof AdminWalkinRemindersRoute
  '/admin/walkin/schedules': typeof AdminWalkinSchedulesRoute
  '/admin/walkin/vehicles': typeof AdminWalkinVehiclesRouteWithChildren
  '/admin/walkin/': typeof AdminWalkinIndexRoute
  '/admin/walkin/customers/$customerId': typeof AdminWalkinCustomersCustomerIdRoute
  '/admin/walkin/vehicles/$vehicleId': typeof AdminWalkinVehiclesVehicleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/my-car'
    | '/report'
    | '/request-access'
    | '/reset-password'
    | '/vehicles'
    | '/admin/appointments'
    | '/admin/clients'
    | '/admin/pricing'
    | '/admin/requests'
    | '/admin/schedules'
    | '/admin/select'
    | '/admin/service-log'
    | '/admin/vehicles'
    | '/admin/walkin'
    | '/my-car/appointments'
    | '/my-car/book'
    | '/my-car/history'
    | '/vehicles/$unitId'
    | '/my-car/'
    | '/admin/walkin/appointments'
    | '/admin/walkin/customers'
    | '/admin/walkin/reminders'
    | '/admin/walkin/schedules'
    | '/admin/walkin/vehicles'
    | '/admin/walkin/'
    | '/admin/walkin/customers/$customerId'
    | '/admin/walkin/vehicles/$vehicleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/report'
    | '/request-access'
    | '/reset-password'
    | '/vehicles'
    | '/admin/appointments'
    | '/admin/clients'
    | '/admin/pricing'
    | '/admin/requests'
    | '/admin/schedules'
    | '/admin/select'
    | '/admin/service-log'
    | '/admin/vehicles'
    | '/my-car/appointments'
    | '/my-car/book'
    | '/my-car/history'
    | '/vehicles/$unitId'
    | '/my-car'
    | '/admin/walkin/appointments'
    | '/admin/walkin/customers'
    | '/admin/walkin/reminders'
    | '/admin/walkin/schedules'
    | '/admin/walkin/vehicles'
    | '/admin/walkin'
    | '/admin/walkin/customers/$customerId'
    | '/admin/walkin/vehicles/$vehicleId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/my-car'
    | '/report'
    | '/request-access'
    | '/reset-password'
    | '/vehicles'
    | '/admin/appointments'
    | '/admin/clients'
    | '/admin/pricing'
    | '/admin/requests'
    | '/admin/schedules'
    | '/admin/select'
    | '/admin/service-log'
    | '/admin/vehicles'
    | '/admin/walkin'
    | '/my-car/appointments'
    | '/my-car/book'
    | '/my-car/history'
    | '/vehicles/$unitId'
    | '/my-car/'
    | '/admin/walkin/appointments'
    | '/admin/walkin/customers'
    | '/admin/walkin/reminders'
    | '/admin/walkin/schedules'
    | '/admin/walkin/vehicles'
    | '/admin/walkin/'
    | '/admin/walkin/customers/$customerId'
    | '/admin/walkin/vehicles/$vehicleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  MyCarRoute: typeof MyCarRouteWithChildren
  ReportRoute: typeof ReportRoute
  RequestAccessRoute: typeof RequestAccessRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VehiclesRoute: typeof VehiclesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vehicles': {
      id: '/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof VehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-access': {
      id: '/request-access'
      path: '/request-access'
      fullPath: '/request-access'
      preLoaderRoute: typeof RequestAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-car': {
      id: '/my-car'
      path: '/my-car'
      fullPath: '/my-car'
      preLoaderRoute: typeof MyCarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-car/': {
      id: '/my-car/'
      path: '/'
      fullPath: '/my-car/'
      preLoaderRoute: typeof MyCarIndexRouteImport
      parentRoute: typeof MyCarRoute
    }
    '/vehicles/$unitId': {
      id: '/vehicles/$unitId'
      path: '/$unitId'
      fullPath: '/vehicles/$unitId'
      preLoaderRoute: typeof VehiclesUnitIdRouteImport
      parentRoute: typeof VehiclesRoute
    }
    '/my-car/history': {
      id: '/my-car/history'
      path: '/history'
      fullPath: '/my-car/history'
      preLoaderRoute: typeof MyCarHistoryRouteImport
      parentRoute: typeof MyCarRoute
    }
    '/my-car/book': {
      id: '/my-car/book'
      path: '/book'
      fullPath: '/my-car/book'
      preLoaderRoute: typeof MyCarBookRouteImport
      parentRoute: typeof MyCarRoute
    }
    '/my-car/appointments': {
      id: '/my-car/appointments'
      path: '/appointments'
      fullPath: '/my-car/appointments'
      preLoaderRoute: typeof MyCarAppointmentsRouteImport
      parentRoute: typeof MyCarRoute
    }
    '/admin/walkin': {
      id: '/admin/walkin'
      path: '/walkin'
      fullPath: '/admin/walkin'
      preLoaderRoute: typeof AdminWalkinRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vehicles': {
      id: '/admin/vehicles'
      path: '/vehicles'
      fullPath: '/admin/vehicles'
      preLoaderRoute: typeof AdminVehiclesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/service-log': {
      id: '/admin/service-log'
      path: '/service-log'
      fullPath: '/admin/service-log'
      preLoaderRoute: typeof AdminServiceLogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/select': {
      id: '/admin/select'
      path: '/select'
      fullPath: '/admin/select'
      preLoaderRoute: typeof AdminSelectRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/schedules': {
      id: '/admin/schedules'
      path: '/schedules'
      fullPath: '/admin/schedules'
      preLoaderRoute: typeof AdminSchedulesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/appointments': {
      id: '/admin/appointments'
      path: '/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AdminAppointmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/walkin/': {
      id: '/admin/walkin/'
      path: '/'
      fullPath: '/admin/walkin/'
      preLoaderRoute: typeof AdminWalkinIndexRouteImport
      parentRoute: typeof AdminWalkinRoute
    }
    '/admin/walkin/vehicles': {
      id: '/admin/walkin/vehicles'
      path: '/vehicles'
      fullPath: '/admin/walkin/vehicles'
      preLoaderRoute: typeof AdminWalkinVehiclesRouteImport
      parentRoute: typeof AdminWalkinRoute
    }
    '/admin/walkin/schedules': {
      id: '/admin/walkin/schedules'
      path: '/schedules'
      fullPath: '/admin/walkin/schedules'
      preLoaderRoute: typeof AdminWalkinSchedulesRouteImport
      parentRoute: typeof AdminWalkinRoute
    }
    '/admin/walkin/reminders': {
      id: '/admin/walkin/reminders'
      path: '/reminders'
      fullPath: '/admin/walkin/reminders'
      preLoaderRoute: typeof AdminWalkinRemindersRouteImport
      parentRoute: typeof AdminWalkinRoute
    }
    '/admin/walkin/customers': {
      id: '/admin/walkin/customers'
      path: '/customers'
      fullPath: '/admin/walkin/customers'
      preLoaderRoute: typeof AdminWalkinCustomersRouteImport
      parentRoute: typeof AdminWalkinRoute
    }
    '/admin/walkin/appointments': {
      id: '/admin/walkin/appointments'
      path: '/appointments'
      fullPath: '/admin/walkin/appointments'
      preLoaderRoute: typeof AdminWalkinAppointmentsRouteImport
      parentRoute: typeof AdminWalkinRoute
    }
    '/admin/walkin/vehicles/$vehicleId': {
      id: '/admin/walkin/vehicles/$vehicleId'
      path: '/$vehicleId'
      fullPath: '/admin/walkin/vehicles/$vehicleId'
      preLoaderRoute: typeof AdminWalkinVehiclesVehicleIdRouteImport
      parentRoute: typeof AdminWalkinVehiclesRoute
    }
    '/admin/walkin/customers/$customerId': {
      id: '/admin/walkin/customers/$customerId'
      path: '/$customerId'
      fullPath: '/admin/walkin/customers/$customerId'
      preLoaderRoute: typeof AdminWalkinCustomersCustomerIdRouteImport
      parentRoute: typeof AdminWalkinCustomersRoute
    }
  }
}

interface AdminWalkinCustomersRouteChildren {
  AdminWalkinCustomersCustomerIdRoute: typeof AdminWalkinCustomersCustomerIdRoute
}

const AdminWalkinCustomersRouteChildren: AdminWalkinCustomersRouteChildren = {
  AdminWalkinCustomersCustomerIdRoute: AdminWalkinCustomersCustomerIdRoute,
}

const AdminWalkinCustomersRouteWithChildren =
  AdminWalkinCustomersRoute._addFileChildren(AdminWalkinCustomersRouteChildren)

interface AdminWalkinVehiclesRouteChildren {
  AdminWalkinVehiclesVehicleIdRoute: typeof AdminWalkinVehiclesVehicleIdRoute
}

const AdminWalkinVehiclesRouteChildren: AdminWalkinVehiclesRouteChildren = {
  AdminWalkinVehiclesVehicleIdRoute: AdminWalkinVehiclesVehicleIdRoute,
}

const AdminWalkinVehiclesRouteWithChildren =
  AdminWalkinVehiclesRoute._addFileChildren(AdminWalkinVehiclesRouteChildren)

interface AdminWalkinRouteChildren {
  AdminWalkinAppointmentsRoute: typeof AdminWalkinAppointmentsRoute
  AdminWalkinCustomersRoute: typeof AdminWalkinCustomersRouteWithChildren
  AdminWalkinRemindersRoute: typeof AdminWalkinRemindersRoute
  AdminWalkinSchedulesRoute: typeof AdminWalkinSchedulesRoute
  AdminWalkinVehiclesRoute: typeof AdminWalkinVehiclesRouteWithChildren
  AdminWalkinIndexRoute: typeof AdminWalkinIndexRoute
}

const AdminWalkinRouteChildren: AdminWalkinRouteChildren = {
  AdminWalkinAppointmentsRoute: AdminWalkinAppointmentsRoute,
  AdminWalkinCustomersRoute: AdminWalkinCustomersRouteWithChildren,
  AdminWalkinRemindersRoute: AdminWalkinRemindersRoute,
  AdminWalkinSchedulesRoute: AdminWalkinSchedulesRoute,
  AdminWalkinVehiclesRoute: AdminWalkinVehiclesRouteWithChildren,
  AdminWalkinIndexRoute: AdminWalkinIndexRoute,
}

const AdminWalkinRouteWithChildren = AdminWalkinRoute._addFileChildren(
  AdminWalkinRouteChildren,
)

interface AdminRouteChildren {
  AdminAppointmentsRoute: typeof AdminAppointmentsRoute
  AdminClientsRoute: typeof AdminClientsRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminRequestsRoute: typeof AdminRequestsRoute
  AdminSchedulesRoute: typeof AdminSchedulesRoute
  AdminSelectRoute: typeof AdminSelectRoute
  AdminServiceLogRoute: typeof AdminServiceLogRoute
  AdminVehiclesRoute: typeof AdminVehiclesRoute
  AdminWalkinRoute: typeof AdminWalkinRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAppointmentsRoute: AdminAppointmentsRoute,
  AdminClientsRoute: AdminClientsRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminRequestsRoute: AdminRequestsRoute,
  AdminSchedulesRoute: AdminSchedulesRoute,
  AdminSelectRoute: AdminSelectRoute,
  AdminServiceLogRoute: AdminServiceLogRoute,
  AdminVehiclesRoute: AdminVehiclesRoute,
  AdminWalkinRoute: AdminWalkinRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MyCarRouteChildren {
  MyCarAppointmentsRoute: typeof MyCarAppointmentsRoute
  MyCarBookRoute: typeof MyCarBookRoute
  MyCarHistoryRoute: typeof MyCarHistoryRoute
  MyCarIndexRoute: typeof MyCarIndexRoute
}

const MyCarRouteChildren: MyCarRouteChildren = {
  MyCarAppointmentsRoute: MyCarAppointmentsRoute,
  MyCarBookRoute: MyCarBookRoute,
  MyCarHistoryRoute: MyCarHistoryRoute,
  MyCarIndexRoute: MyCarIndexRoute,
}

const MyCarRouteWithChildren = MyCarRoute._addFileChildren(MyCarRouteChildren)

interface VehiclesRouteChildren {
  VehiclesUnitIdRoute: typeof VehiclesUnitIdRoute
}

const VehiclesRouteChildren: VehiclesRouteChildren = {
  VehiclesUnitIdRoute: VehiclesUnitIdRoute,
}

const VehiclesRouteWithChildren = VehiclesRoute._addFileChildren(
  VehiclesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  MyCarRoute: MyCarRouteWithChildren,
  ReportRoute: ReportRoute,
  RequestAccessRoute: RequestAccessRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VehiclesRoute: VehiclesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
